version: '3.9'

services:
  web:
    build: .
    container_name: ocrdjango-web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DJANGO_DEBUG=1
      - ALLOWED_HOSTS=*
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
      ollama-pull:
        condition: service_completed_successfully

  ollama:
    image: ollama/ollama:0.5.4
    container_name: ocrdjango-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 30s
      timeout: 10s
      retries: 10

  ollama-pull:
    image: ollama/ollama:0.5.4
    container_name: ocrdjango-ollama-pull
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: >
      /bin/bash -c "
      until curl --output /dev/null --silent --head --fail http://ollama:11434; do
        printf 'waiting for ollama server to be ready...'
        sleep 5
      done;
      ollama pull llama3.2-vision:11b
      "
    restart: "no"

volumes:
  ollama: