version: '3.9'

services:
  web:
    build: .
    container_name: ocrdjango-web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./uploads:/tmp/uploads
    environment:
      - DJANGO_DEBUG=1
      - ALLOWED_HOSTS=*
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
      ollama-pull:
        condition: service_completed_successfully
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ocrdjango-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 30s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ocrdjango-ollama-pull
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: >
      /bin/bash -c "
      until ollama list; do
        echo 'waiting for ollama server to be ready...'
        sleep 5
      done;
      ollama pull llama3.2:3b
      "
    restart: "no"

volumes:
  ollama:
